spring.application.name=user_service

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/order
spring.datasource.username=root
spring.datasource.password=Monu@20345092
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# Zipkin (Micrometer Tracing)
# ===============================
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# ===============================
# Eureka Client
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=*

# ===============================
# Logging with Trace & Span ID
# ===============================
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %5p [${spring.application.name},%X{traceId},%X{spanId}] %logger{36} - %msg%n

server.port=8082
